services:
  mypiagent:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhost/ykpmusicstudio/pi-dockerized:latest
    container_name: mypiagent
    ports:
      - "8893:8893"

    tty: true
    stdin_open: true

    environment:
      - HTTP_PORT=8893
      - IP_ADDR=0.0.0.0
      - PI_WEB_CONFIG=/pi-config/.pi-web
      - PI_CODING_AGENT_DIR=/pi-config
      - REPO_ROOT=/app
      - PI_WEB_ALLOWED_HOSTS=localhost

    volumes:
      - app:/app
      - pi_config:/pi-config
      - pi_extensions:/pi-extensions

    user: "${UID:-1000}:${GID:-1000}"

    networks:
      - pi-network

    restart: "no"

volumes:
  pi_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.tests/pi-config

  pi_extensions:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.tests/pi-extensions

  app:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/.tests/app

networks:
    pi-network:
      driver: bridge
